Repository mohit-dhote/Codify-Platform, pull requests merged in 2023-10, with the labels that each got.

#19 Create Kadane's Algorithm
  Add Code Here/CPP/Kadane's Algorithm
Labels: hacktoberfest accepted

#20 Create Best Time to Buy and Sell Stock
  Add Code Here/CPP/Best Time to Buy and Sell Stock
Labels: hacktoberfest accepted

#22 Profile Picture Added
  static/images/AVDeshmukh.jpg
Labels: hacktoberfest accepted

#25 Create Sudoku.py
  Add Code Here/Python/Sudoku.py
Labels: hacktoberfest accepted

#27 [Hacktoberfest'23] : Added Myself
  content/participant /Ashish Mishra.md
  static/images/Ashish Mishra.jpg
Labels: hacktoberfest accepted

#28 Added Column_name_from_given_column_number.py a GFG problem
  Add Code Here/Python/Column_name_from_given_column_number.py
Labels: hacktoberfest accepted

#30 Update voice feedback chatbot.py file
  Add Code Here/Python/chatbot.py
Labels: hacktoberfest accepted

#31 Create Kalyani.md
  Add Code Here/Python/chatbot.py
  Participants/Kalyani.md
Labels: Hacktoberfest-approved, hacktoberfest accepted

#32 Python Program for using macros
  Add Code Here/Python/Python Macro Programmer/Macro_Programmer.py
  Add Code Here/Python/Python Macro Programmer/Macros.txt
  content/participant /NIGHTFURY2111.md
  static/images/NIGHTFURY2111.png
Labels: Hacktoberfest-approved, hacktoberfest accepted

#33 Adding Java Programs
  Add Code Here/CPP/0-1 Knapsack
  Add Code Here/CPP/2ndMaximumAmong3Numbers.c++
  Add Code Here/CPP/AVL Tree Implementation.cpp
  Add Code Here/CPP/Binary_search.cpp
  Add Code Here/CPP/Binary_search_usingrecursion.cpp
  Add Code Here/CPP/Bit_Difference.cpp
  Add Code Here/CPP/Bitset.cpp
  Add Code Here/CPP/Boruvka's_algorithm.cpp
  Add Code Here/CPP/BubbleSort.cpp
  Add Code Here/CPP/Calculating Area of 2D shapes.cpp
  Add Code Here/CPP/Check Armstrong Number of any number of digit.cpp
  Add Code Here/CPP/CheckTwoNodesOnSamePath.cpp
  Add Code Here/CPP/Check_if_a_queue_can_be_sorted_into_another_queue_using_a_stack.cpp
  Add Code Here/CPP/ChocolateProblem.cpp
  Add Code Here/CPP/Cyclically rotate an array by one.cpp
  Add Code Here/CPP/Detect Cycle in singly linked list.cpp
  Add Code Here/CPP/Dijkstra's single source shortest path algorithm.cpp
  Add Code Here/CPP/add_two_numbers_represented_by_linked_lists.cpp
  Add Code Here/CPP/array-of-vectors.cpp
  Add Code Here/CPP/articulation_points.cpp
  Add Code Here/CPP/count_set_bits.cpp
  Add Code Here/CPP/countsort.cpp
  Add Code Here/CPP/cycle_detection_using_dsu.cpp
  Add Code Here/CPP/decode_ways.cpp
  Add Code Here/JAVA/CheckBST.java
  Add Code Here/JAVA/EvenAfterOddLL.java
  Add Code Here/JAVA/ExecuteBinarySearchOnAVector.java
  Add Code Here/JAVA/Happy Number.java
  Add Code Here/JAVA/InorderSuccessorInBinaryTree.java
  Add Code Here/JAVA/LeftViewOfBinaryTree.java
  Add Code Here/JAVA/Linked List Cycle.java
  Add Code Here/JAVA/ListNode.java
  Add Code Here/JAVA/MidElementDeletion.java
  Add Code Here/JAVA/Palindrome_Number.java
  Add Code Here/JAVA/Radix.java
  Add Code Here/JAVA/Remove_element.java
  Add Code Here/JAVA/ReversePath.java
  Add Code Here/JAVA/Reverse_queue.java
  Add Code Here/JAVA/RotateMatrixBy90Degrees.java
  Add Code Here/JAVA/Selection_sort.java
  Add Code Here/JAVA/SubtreeDifference.java
  Add Code Here/JAVA/TernarySearch.java
  Add Code Here/JAVA/TrappingRainWater.java
  Add Code Here/JAVA/anagrams.java
  Add Code Here/JAVA/bubble_sort.java
  Add Code Here/JAVA/javaAwt.java
  Add Code Here/JAVA/kadane_algo.java
  Add Code Here/JAVA/kth _min_max_element
  Add Code Here/JAVA/linear_search.java
  Add Code Here/JAVA/max_sum_of_array.java
  Add Code Here/JAVA/merge_sort.java
  Add Code Here/JAVA/minSubtree.java
  Add Code Here/JAVA/minValueNodeinBST.java
  Add Code Here/JAVA/tic_tac_toe.java
  Add Code Here/JavaScript/Longest Common Prefix.js
  Add Code Here/JavaScript/Pascal's Triangle.js
  Add Code Here/JavaScript/schemeRandomNota.js
  Add Code Here/JavaScript/top three repeated numbers.js
Labels: Hacktoberfest-approved, hacktoberfest accepted

#34 Create intersection_linked_lists.java
  Add Code Here/JAVA/intersection_linked_lists.java
Labels: Hacktoberfest-approved, hacktoberfest accepted

#42 Adding Sorting Algorithms in Cpp, issue No. #38
  Add Code Here/CPP/Bubble_Sort.cpp
  Add Code Here/CPP/Heap_Sort.cpp
  Add Code Here/CPP/Insertion_Sort.cpp
  Add Code Here/CPP/Merge_Sort.cpp
  Add Code Here/CPP/Quick_Sort.cpp
  Add Code Here/CPP/Selection_Sort.cpp
Labels: Hacktoberfest2023, hacktoberfest accepted

#43 Added logistic_regression_implementation.py
  Add Code Here/Python/logistic_regression_implementation.py
Labels: Hacktoberfest2023, hacktoberfest accepted

#44 Add files via upload
  Add Code Here/CPP/sorting_techniques.cpp
Labels: Hacktoberfest2023, hacktoberfest accepted

#53 Added Boundary Traversal of Matrix.cpp
  Add Code Here/CPP/Boundary Traversal Matrix.cpp
Labels: Hacktoberfest2023, hacktoberfest accepted

#56 Added decision_tree_implementation.py
  Add Code Here/Python/decision_tree_implementation.py
Labels: Hacktoberfest2023, hacktoberfest accepted

#52 Create Swap Nodes in Pairs.cpp
  Add Code Here/CPP/Swap Nodes in Pairs.cpp
Labels: Hacktoberfest2023, hacktoberfest accepted

#55 Added Sieve of Eratosthenes.cpp
  Add Code Here/CPP/Sieve of Eratosthenes.cpp
Labels: Hacktoberfest2023, hacktoberfest accepted

#54 Major changes to python macro programmer
  Add Code Here/Python/Python Macro Programmer/Cmd_Interface.py
  Add Code Here/Python/Python Macro Programmer/Macro.json
  Add Code Here/Python/Python Macro Programmer/Macro_Programmer.py
  Add Code Here/Python/Python Macro Programmer/Macros.txt
Labels: Hacktoberfest2023, hacktoberfest accepted

#59 Create linearRegressionInJS.js
  Add Code Here/JavaScript/linearRegressionInJS.js
Labels: Hacktoberfest2023, hacktoberfest accepted

#61 Create Linear_Regression_Implementation_from_scratch.py
  Add Code Here/Python/Linear_Regression_Implementation_from_scratch.py
Labels: Hacktoberfest2023, hacktoberfest accepted

#62 Create MergeSort.java
  Add Code Here/Java/MergeSort.java
Labels: Hacktoberfest2023, hacktoberfest accepted

#65 Create Logistic_regression_implementation_from_scratch.py
  Add Code Here/Python/Logistic_regression_implementation_from_scratch.py
Labels: Hacktoberfest2023, hacktoberfest accepted

#67 Create GnomeSort.java
  Add Code Here/JAVA/GnomeSort.java
Labels: Hacktoberfest2023, hacktoberfest accepted

#68 Added a fun GPT-assistant.
  Add Code Here/Python/Python Macro Programmer/gpt-assisstant.py
Labels: Hacktoberfest2023, hacktoberfest accepted

#69 added K Nearest Neighbors implementation
  Add Code Here/Python/k_nearest_neighbors.py
Labels: Hacktoberfest2023, hacktoberfest accepted

#70 Update add_two_numbers_represented_by_linked_lists.cpp
  Add Code Here/CPP/add_two_numbers_represented_by_linked_lists.cpp
Labels: Hacktoberfest2023, hacktoberfest accepted

#71 Create checkstringsanagram.java
  Add Code Here/Java/checkstringsanagram.java
Labels: Hacktoberfest2023, hacktoberfest accepted

#72 Create L2_regularization_Implementation_from_scratch.py
  Add Code Here/Python/L2_regularization_Implementation_from_scratch.py
Labels: Hacktoberfest2023, hacktoberfest accepted

#73 updated Macro Programmer, refactored code, enhanced User experience and fixed some minor bugs
  Add Code Here/Python/Python Macro Programmer/Cmd_Interface.py
  Add Code Here/Python/Python Macro Programmer/Macro.json
  Add Code Here/Python/Python Macro Programmer/Macro_Programmer.py
Labels: Hacktoberfest2023, hacktoberfest accepted

#78 Added a Joke Teller program written in CPP.
  Add Code Here/CPP/joke-teller.cpp
Labels: hacktoberfest accepted

#79 added 2-Queue_using_Array_C++.cpp
  Add Code Here/CPP/2-Queue_using_Array_C++.cpp
Labels: hacktoberfest accepted

#80 ADDED A PROBLEM FINDING THE LONGEST INCREASING SUBSEQUENCE.
  Add Code Here/CPP/array1.cpp
Labels: Hacktoberfest2023, hacktoberfest accepted

#81 added heart disease prediction model
  Add Code Here/Python/heart_disease_prediction_model/cleveland.csv
  Add Code Here/Python/heart_disease_prediction_model/framingham.csv
  Add Code Here/Python/heart_disease_prediction_model/heart.ipynb
Labels: Hacktoberfest2023, Hacktoberfest-approved, hacktoberfest accepted

#83 Dijkstra's Algorithm
  Add Code Here/CPP/Dijkstra's_Algo.cpp
Labels: Hacktoberfest2023, hacktoberfest accepted

#84 Create kmalhotra08 basketball game
  Add Code Here/JavaScript/kmalhotra08 basketball game
Labels: Hacktoberfest2023, Hacktoberfest-approved, hacktoberfest accepted

#85 Create kmalhotra08 contributor
  Participants/kmalhotra08 contributor
Labels: hacktoberfest, Hacktoberfest-approved, hacktoberfest accepted

#86 Update Hangman.py
  Add Code Here/Python/Hangman.py
Labels: Hacktoberfest2023, hacktoberfest accepted

#87 DeepNeuralNetwork on MNIST dataset
  Add Code Here/Python/deepneuralnetwork_mnist.py
Labels: Hacktoberfest2023, hacktoberfest accepted

#89 added Taylor_Series_using_recursion.cpp
  Add Code Here/CPP/Factorial_of_a_Number_using_recursion.cpp
  Add Code Here/CPP/Taylor_Series_using_recursion.cpp
Labels: Hacktoberfest2023, Hacktoberfest-approved

#90 added Parenthesis_Matching_using_Stack.cpp
  Add Code Here/CPP/Parenthesis_Matching_using_Stack.cpp
Labels: Hacktoberfest2023, hacktoberfest accepted

#92 Added Quick sort using python
  Add Code Here/Python/quick sort.py
Labels: Hacktoberfest2023, hacktoberfest accepted

#94 added NthPrime.py
  Add Code Here/Python/NthPrime.py
Labels: Hacktoberfest2023, hacktoberfest accepted
